name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CI: true

jobs:
  UI_UT:
    env:
      UI_UT: true
    runs-on:
      - ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.2'

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: 'd6e8b07c-4a52-4fec-ada4-2b4b24fcc069'
          file: ./coverage/cobertura-coverage.xml

